"""add profile and description columns

Revision ID: 01cf6f0baf84
Revises: 20260517_0001
Create Date: 2026-06-11 02:08:26.352311
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '01cf6f0baf84'
down_revision: str | None = '20260517_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('permissions', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('roles', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_column('users', 'name')
    op.drop_column('roles', 'description')
    op.drop_column('permissions', 'description')
    op.drop_column('organizations', 'description')
    # ### end Alembic commands ###
